image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test

variables:
  TEST_IMAGE: registry.gitlab.com/srz-zumix/iutest-test:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  except:
    - schedules
  script:
    - docker build --pull -t $TEST_IMAGE -f .ci/Dockerfile.gitlab .
    - docker push $TEST_IMAGE

test:
  stage: test
  except:
    - schedules
  script:
    - docker pull $TEST_IMAGE
    - docker run -v $(pwd):/iutest-test $TEST_IMAGE

update_submodule:
  stage: build
  only:
    - schedules
  before_script:
    - apk update && apk add git
    - 'which ssh-agent || ( apk add openssh )'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email 'zumix.cpp@gmail.com'
    - git config --global user.name 'srz_zumix (GitLab CI)'
  script:
    - ssh git@gitlab.com
    - git checkout ${CI_COMMIT_REF_NAME}
    - git submodule foreach git pull origin master
    - git add -A
    - git commit -m "update head" || true
    - git push git@gitlab.com:srz-zumix/iutest-test.git ${CI_COMMIT_REF_NAME}

