image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test

variables:
  TEST_IMAGE: registry.gitlab.com/srz-zumix/iutest-test:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  except:
    - schedules
  script:
    - docker build --pull -t $TEST_IMAGE -f .ci/Dockerfile.gitlab .
    - docker push $TEST_IMAGE

test:
  stage: test
  except:
    - schedules
  script:
    - docker pull $TEST_IMAGE
    - docker run -v $(pwd):/iutest-test $TEST_IMAGE

update_submodule:
  stage: build
  only:
    - schedules
  before_script:
    - apk update && apk add git
  script:
    - git clone https://${GITLAB_USER_NAME}:${GITLAB_CI_PASS}@gitlab.com/${CI_PROJECT_PATH}.git iutest-test
    - cd iutest-test
    - git config --global user.email 'zumix.cpp@gmail.com'
    - git config --global user.name 'srz_zumix (GitLab CI)'
    - git checkout ${CI_COMMIT_REF_NAME}
    - git submodule foreach git pull origin master
    - git add -A
    - git commit -m "update head" || true
    - git push origin ${CI_COMMIT_REF_NAME}

